server:
  port: 8999
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8777/eureka/
spring:
  application:
    name: authservice
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888
      enabled: true
      fail-fast: true